# ------------------------------------------------------------------------
# INDEX PAGE
# ------------------------------------------------------------------------
# title - main text (long text)
# desc - description text (long text)
# ------------------------------------------------------------------------

title: |
  Welcome to Purple World
desc: | 
  A whitelisted free-to-play roleplay FiveM server
